server:
  port: 8888

spring:
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    template:
      mandatory: true
    publisher-confirms: true #消息确认机制，确认回调
    publisher-returns: true #消息确认机制，返回回调
    listener:
      simple:
        acknowledge-mode: manual #手动应答
        concurrency: 1 #最小消费者数量
        max-concurrency: 10 # 最大消费者数
        retry:
          enabled: true #是否支持重试
          max-attempts: 3

#          #spring.rabbitmq.virtual-host=/
#          spring.rabbitmq.template.mandatory=true
#          # 消息发送至exchange callback
#          spring.rabbitmq.publisher-confirms=true
#          # 消息发送至queue 失败才callback
#          spring.rabbitmq.publisher-returns=true
#          # 消费消息手动删除
#          spring.rabbitmq.listener.simple.acknowledge-mode=manual
#